version: 2.1

orbs:
  node: circleci/node@4.9.0

jobs:
  build:
    docker:
      - image: cimg/node:<< parameters.node-version >>
    steps:
      - checkout
      - run: npm install
      - run: npm test
    parameters:
      node-version:
        default: "18.16"
        type: string
